eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka}
  instance:
    hostname: localhost
